export { default as getDogs } from './getDogs'
export { default as getDog } from './getDog'
export { default as postDog } from './postDog'
export { default as patchDog } from './patchDog'
export { default as deleteDog } from './deleteDog'
export { default as postDogImages } from './postDogImages'
export { default as deleteDogImage } from './deleteDogImage'
export { default as getDogImages } from './getDogImages'
