export { default as About } from './About'
export { default as Dogs } from './Dogs'
export { default as Home } from './Home/Home'
export { default as Contacts } from './Contacts/Contacts'
export { default as NotFound } from './NotFound/NotFound'
